import type { FoodItem } from "./seed-foods";

// Sample foods with common Nepal and international foods
// Nutrition per serving based on USDA data
export const sampleFoods: FoodItem[] = [
  {
    name: "Cooked rice",
    brand: null,
    source: "verified" as const,
    servingSize: 200,
    servingUnit: "g",
    householdServing: "1 bowl",
    calories: 260,
    nutrients: { protein: 4.4, fat: 0.4, carbs: 57.4, fiber: 0.6, sodium: 2, potassium: 56 },
  },
  {
    name: "Chicken breast",
    brand: null,
    source: "verified" as const,
    servingSize: 100,
    servingUnit: "g",
    householdServing: "1 serving",
    calories: 165,
    nutrients: { protein: 31, fat: 3.6, carbs: 0, fiber: 0, sodium: 74, potassium: 256 },
  },
  {
    name: "Egg",
    brand: null,
    source: "verified" as const,
    servingSize: 50,
    servingUnit: "g",
    householdServing: "1 egg",
    calories: 72,
    nutrients: { protein: 6.3, fat: 4.8, carbs: 0.4, fiber: 0, sodium: 71, potassium: 69 },
  },
  {
    name: "Banana",
    brand: null,
    source: "verified" as const,
    servingSize: 118,
    servingUnit: "g",
    householdServing: "1 medium banana",
    calories: 105,
    nutrients: { protein: 1.3, fat: 0.4, carbs: 27, fiber: 3.1, sodium: 1, potassium: 422 },
  },
  {
    name: "Apple",
    brand: null,
    source: "verified" as const,
    servingSize: 182,
    servingUnit: "g",
    householdServing: "1 medium apple",
    calories: 95,
    nutrients: { protein: 0.5, fat: 0.3, carbs: 25, fiber: 4.4, sodium: 2, potassium: 195 },
  },
  {
    name: "Soy milk",
    brand: null,
    source: "verified" as const,
    servingSize: 240,
    servingUnit: "ml",
    householdServing: "1 cup",
    calories: 80,
    nutrients: { protein: 7, fat: 4, carbs: 4, fiber: 1, sodium: 90, potassium: 300 },
  },
  {
    name: "Whole milk",
    brand: null,
    source: "verified" as const,
    servingSize: 244,
    servingUnit: "ml",
    householdServing: "1 cup",
    calories: 149,
    nutrients: { protein: 8, fat: 8, carbs: 12, fiber: 0, sodium: 105, potassium: 322 },
  },
  {
    name: "Sweet potato",
    brand: null,
    source: "verified" as const,
    servingSize: 130,
    servingUnit: "g",
    householdServing: "1 medium piece",
    calories: 112,
    nutrients: { protein: 2, fat: 0.1, carbs: 26, fiber: 3.8, sodium: 72, potassium: 438 },
  },
  {
    name: "Oats",
    brand: null,
    source: "verified" as const,
    servingSize: 40,
    servingUnit: "g",
    householdServing: "1/2 cup",
    calories: 150,
    nutrients: { protein: 5, fat: 2.5, carbs: 27, fiber: 4, sodium: 0, potassium: 143 },
  },
  {
    name: "Broccoli",
    brand: null,
    source: "verified" as const,
    servingSize: 91,
    servingUnit: "g",
    householdServing: "1 cup chopped",
    calories: 31,
    nutrients: { protein: 2.6, fat: 0.3, carbs: 6, fiber: 2.4, sodium: 30, potassium: 288 },
  },
  {
    name: "Salmon",
    brand: null,
    source: "verified" as const,
    servingSize: 100,
    servingUnit: "g",
    householdServing: "1 fillet",
    calories: 208,
    nutrients: { protein: 20, fat: 13, carbs: 0, fiber: 0, sodium: 59, potassium: 363 },
  },
  {
    name: "Avocado",
    brand: null,
    source: "verified" as const,
    servingSize: 68,
    servingUnit: "g",
    householdServing: "1/3 avocado",
    calories: 109,
    nutrients: { protein: 1.3, fat: 10, carbs: 6, fiber: 4.6, sodium: 5, potassium: 329 },
  },
  {
    name: "Tofu",
    brand: null,
    source: "verified" as const,
    servingSize: 126,
    servingUnit: "g",
    householdServing: "1/2 block",
    calories: 88,
    nutrients: { protein: 9.2, fat: 5.3, carbs: 2.2, fiber: 0.4, sodium: 10, potassium: 150 },
  },
  {
    name: "Whole wheat bread",
    brand: null,
    source: "verified" as const,
    servingSize: 43,
    servingUnit: "g",
    householdServing: "1 slice",
    calories: 110,
    nutrients: { protein: 5, fat: 1.5, carbs: 20, fiber: 3, sodium: 170, potassium: 100 },
  },
  {
    name: "Greek yogurt",
    brand: null,
    source: "verified" as const,
    servingSize: 170,
    servingUnit: "g",
    householdServing: "1 cup",
    calories: 100,
    nutrients: { protein: 17, fat: 0.7, carbs: 6, fiber: 0, sodium: 65, potassium: 240 },
  },
  {
    name: "Dal bhat tarkari",
    brand: null,
    source: "verified" as const,
    servingSize: 450,
    servingUnit: "g",
    householdServing: "1 plate",
    calories: 650,
    nutrients: { protein: 22, fat: 16, carbs: 105, fiber: 10, sodium: 780, potassium: 780 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Plain dal",
    brand: null,
    source: "verified" as const,
    servingSize: 240,
    servingUnit: "g",
    householdServing: "1 bowl",
    calories: 190,
    nutrients: { protein: 11, fat: 5, carbs: 27, fiber: 8, sodium: 420, potassium: 520 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Bhat",
    brand: null,
    source: "verified" as const,
    servingSize: 250,
    servingUnit: "g",
    householdServing: "1 plate rice",
    calories: 325,
    nutrients: { protein: 6, fat: 0.6, carbs: 72, fiber: 0.8, sodium: 3, potassium: 70 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Aloo tarkari",
    brand: null,
    source: "verified" as const,
    servingSize: 180,
    servingUnit: "g",
    householdServing: "1 bowl",
    calories: 210,
    nutrients: { protein: 4, fat: 8, carbs: 32, fiber: 5, sodium: 480, potassium: 640 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Gundruk ko jhol",
    brand: null,
    source: "verified" as const,
    servingSize: 220,
    servingUnit: "g",
    householdServing: "1 bowl",
    calories: 95,
    nutrients: { protein: 4, fat: 4, carbs: 12, fiber: 5, sodium: 620, potassium: 360 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Dhido",
    brand: null,
    source: "verified" as const,
    servingSize: 300,
    servingUnit: "g",
    householdServing: "1 serving",
    calories: 330,
    nutrients: { protein: 9, fat: 2.5, carbs: 69, fiber: 8, sodium: 8, potassium: 260 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Sel roti",
    brand: null,
    source: "verified" as const,
    servingSize: 70,
    servingUnit: "g",
    householdServing: "1 piece",
    calories: 250,
    nutrients: { protein: 4, fat: 10, carbs: 37, sugar: 8, fiber: 1.2, sodium: 120, potassium: 95 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Chiura",
    brand: null,
    source: "verified" as const,
    servingSize: 60,
    servingUnit: "g",
    householdServing: "1 cup",
    calories: 215,
    nutrients: { protein: 4, fat: 0.8, carbs: 48, fiber: 1.8, sodium: 4, potassium: 70 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Dahi chiura",
    brand: null,
    source: "verified" as const,
    servingSize: 250,
    servingUnit: "g",
    householdServing: "1 bowl",
    calories: 310,
    nutrients: { protein: 10, fat: 6, carbs: 55, sugar: 12, fiber: 2, sodium: 95, potassium: 360 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Aloo achar",
    brand: null,
    source: "verified" as const,
    servingSize: 120,
    servingUnit: "g",
    householdServing: "1 small bowl",
    calories: 150,
    nutrients: { protein: 3, fat: 6, carbs: 22, fiber: 4, sodium: 560, potassium: 460 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Aloo tama",
    brand: null,
    source: "verified" as const,
    servingSize: 240,
    servingUnit: "g",
    householdServing: "1 bowl",
    calories: 230,
    nutrients: { protein: 8, fat: 8, carbs: 34, fiber: 8, sodium: 650, potassium: 620 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Chicken momo",
    brand: null,
    source: "verified" as const,
    servingSize: 250,
    servingUnit: "g",
    householdServing: "10 pieces",
    calories: 430,
    nutrients: { protein: 20, fat: 14, carbs: 56, fiber: 3, sodium: 720, potassium: 320 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Buff momo",
    brand: null,
    source: "verified" as const,
    servingSize: 250,
    servingUnit: "g",
    householdServing: "10 pieces",
    calories: 470,
    nutrients: { protein: 22, fat: 18, carbs: 54, fiber: 3, sodium: 760, potassium: 360 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Vegetable momo",
    brand: null,
    source: "verified" as const,
    servingSize: 250,
    servingUnit: "g",
    householdServing: "10 pieces",
    calories: 380,
    nutrients: { protein: 12, fat: 12, carbs: 58, fiber: 5, sodium: 700, potassium: 420 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Momo achar",
    brand: null,
    source: "verified" as const,
    servingSize: 50,
    servingUnit: "g",
    householdServing: "1 serving",
    calories: 55,
    nutrients: { protein: 2, fat: 3, carbs: 6, fiber: 2, sodium: 380, potassium: 160 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Chicken thukpa",
    brand: null,
    source: "verified" as const,
    servingSize: 500,
    servingUnit: "g",
    householdServing: "1 bowl",
    calories: 520,
    nutrients: { protein: 24, fat: 14, carbs: 72, fiber: 5, sodium: 1050, potassium: 620 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Vegetable thukpa",
    brand: null,
    source: "verified" as const,
    servingSize: 500,
    servingUnit: "g",
    householdServing: "1 bowl",
    calories: 420,
    nutrients: { protein: 13, fat: 11, carbs: 68, fiber: 7, sodium: 980, potassium: 680 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Chicken chowmein",
    brand: null,
    source: "verified" as const,
    servingSize: 350,
    servingUnit: "g",
    householdServing: "1 plate",
    calories: 640,
    nutrients: { protein: 26, fat: 22, carbs: 82, fiber: 5, sodium: 1150, potassium: 520 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Vegetable chowmein",
    brand: null,
    source: "verified" as const,
    servingSize: 350,
    servingUnit: "g",
    householdServing: "1 plate",
    calories: 560,
    nutrients: { protein: 15, fat: 20, carbs: 82, fiber: 6, sodium: 1050, potassium: 560 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Chicken curry Nepali style",
    brand: null,
    source: "verified" as const,
    servingSize: 220,
    servingUnit: "g",
    householdServing: "1 bowl",
    calories: 340,
    nutrients: { protein: 29, fat: 21, carbs: 9, fiber: 2, sodium: 620, potassium: 520 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Mutton curry Nepali style",
    brand: null,
    source: "verified" as const,
    servingSize: 220,
    servingUnit: "g",
    householdServing: "1 bowl",
    calories: 430,
    nutrients: { protein: 27, fat: 32, carbs: 8, fiber: 2, sodium: 650, potassium: 480 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Buff sukuti",
    brand: null,
    source: "verified" as const,
    servingSize: 100,
    servingUnit: "g",
    householdServing: "1 serving",
    calories: 320,
    nutrients: { protein: 38, fat: 17, carbs: 4, fiber: 1, sodium: 980, potassium: 520 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Chicken sekuwa",
    brand: null,
    source: "verified" as const,
    servingSize: 150,
    servingUnit: "g",
    householdServing: "1 plate",
    calories: 330,
    nutrients: { protein: 34, fat: 19, carbs: 4, fiber: 1, sodium: 720, potassium: 460 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Buff choila",
    brand: null,
    source: "verified" as const,
    servingSize: 150,
    servingUnit: "g",
    householdServing: "1 plate",
    calories: 360,
    nutrients: { protein: 32, fat: 23, carbs: 6, fiber: 1, sodium: 880, potassium: 520 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Chatamari",
    brand: null,
    source: "verified" as const,
    servingSize: 180,
    servingUnit: "g",
    householdServing: "1 piece",
    calories: 360,
    nutrients: { protein: 16, fat: 14, carbs: 42, fiber: 2, sodium: 520, potassium: 280 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Yomari",
    brand: null,
    source: "verified" as const,
    servingSize: 100,
    servingUnit: "g",
    householdServing: "1 piece",
    calories: 270,
    nutrients: { protein: 4, fat: 5, carbs: 54, sugar: 20, fiber: 2, sodium: 35, potassium: 140 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Bara",
    brand: null,
    source: "verified" as const,
    servingSize: 120,
    servingUnit: "g",
    householdServing: "1 piece",
    calories: 250,
    nutrients: { protein: 12, fat: 12, carbs: 25, fiber: 6, sodium: 460, potassium: 380 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Kwati",
    brand: null,
    source: "verified" as const,
    servingSize: 240,
    servingUnit: "g",
    householdServing: "1 bowl",
    calories: 260,
    nutrients: { protein: 15, fat: 7, carbs: 36, fiber: 11, sodium: 520, potassium: 700 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Nepali roti",
    brand: null,
    source: "verified" as const,
    servingSize: 60,
    servingUnit: "g",
    householdServing: "1 roti",
    calories: 180,
    nutrients: { protein: 6, fat: 3, carbs: 33, fiber: 4, sodium: 160, potassium: 150 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Samosa",
    brand: null,
    source: "verified" as const,
    servingSize: 90,
    servingUnit: "g",
    householdServing: "1 piece",
    calories: 260,
    nutrients: { protein: 5, fat: 14, carbs: 30, fiber: 3, sodium: 420, potassium: 250 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Pakoda",
    brand: null,
    source: "verified" as const,
    servingSize: 120,
    servingUnit: "g",
    householdServing: "1 plate",
    calories: 330,
    nutrients: { protein: 9, fat: 20, carbs: 30, fiber: 4, sodium: 520, potassium: 320 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Milk tea",
    brand: null,
    source: "verified" as const,
    servingSize: 500,
    servingUnit: "ml",
    householdServing: "1 cup",
    calories: 180,
    nutrients: { protein: 5, fat: 6, carbs: 26, fiber: 0, sodium: 60, potassium: 160 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Chana tarkari",
    brand: null,
    source: "verified" as const,
    servingSize: 220,
    servingUnit: "g",
    householdServing: "1 bowl",
    calories: 330,
    nutrients: { protein: 16, fat: 10, carbs: 46, fiber: 12, sodium: 620, potassium: 720 },
    metadata: { cuisine: "Nepali", estimate: true },
  },
  {
    name: "Boiled egg",
    brand: null,
    source: "verified" as const,
    servingSize: 50,
    servingUnit: "g",
    householdServing: "1 egg",
    calories: 78,
    nutrients: { protein: 6.3, fat: 5.3, carbs: 0.6, fiber: 0, sodium: 62, potassium: 63 },
  },
  {
    name: "Saag",
    brand: null,
    source: "verified" as const,
    servingSize: 100,
    servingUnit: "g",
    householdServing: "1 serving cooked",
    calories: 30,
    nutrients: { protein: 3.3, fat: 0.3, carbs: 5.3, fiber: 3.3, sodium: 5, potassium: 502 },
  },
  {
    name: "Mixed nuts",
    brand: null,
    source: "verified" as const,
    servingSize: 30,
    servingUnit: "g",
    householdServing: "1 handful",
    calories: 175,
    nutrients: { protein: 5, fat: 15, saturatedFat: 2, transFat: 0, carbs: 7, sugar: 1.5, fiber: 2, sodium: 3, potassium: 180 },
  },
];
